In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.simplefilter(action='ignore',category=FutureWarning)

covid_df = pd.read_csv("us_counties_covid19_daily.csv")
covid_df = covid_df.drop(['fips','deaths'],1)
covid_df.head()

         date     county       state  cases
0  2020-01-21  Snohomish  Washington      1
1  2020-01-22  Snohomish  Washington      1
2  2020-01-23  Snohomish  Washington      1
3  2020-01-24       Cook    Illinois      1
4  2020-01-24  Snohomish  Washington      1

In [2]:
# Select data for dense county data
dense_state_county = [
    ('Maryland','Baltimore'),
    ('New Jersey','Essex'),
    ('Illinois','Cook'),
    ('New Jersey','Union'),
    ('Virginia','Norfolk city'),
    ('New York','Nassau'),
    ('Virginia','Harrisonburg city')
]

In [3]:
# Process data for each dense county

# Create new DataFrame to bring data for each county together
dense_county_covid_df = pd.DataFrame()

for state, county in dense_state_county:
    # Get the correct county data
    county_df = covid_df[(covid_df['state'] == state) & (covid_df['county'] == county)].reset_index().drop(['index'],1)

    # new_cases column
    # record the number of new cases for today
    county_df['new_cases'] = pd.Series(dtype=int)

    for i in range(1,len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-1,3]

        county_df.iloc[i,4] = current_cases - previous_cases

    # delta7 column
    # record the change in number of cases from 7 days ago to today
    county_df['delta7'] = pd.Series(dtype=int)

    for i in range(7, len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-7,3]

        county_df.iloc[i,5] = current_cases - previous_cases
    
    # delta14 column
    # record the change in number of cases from 7 days ago to today
    county_df['delta14'] = pd.Series(dtype=int)

    for i in range(14,len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-14,3]

        county_df.iloc[i,6] = current_cases - previous_cases
    
    # remove secondary words like 'city' from county names
    for i in range(0,len(county_df.index)):
        county_df.iloc[i,1] = county.split(' ')[0]

    # Add to final_df
    dense_county_covid_df = pd.concat([dense_county_covid_df,county_df])

# Convert float values to int
dense_county_covid_df = dense_county_covid_df.convert_dtypes()
dense_county_covid_df.head(30)

# make all county and state names lowercase, remove secondary words like 'city'
dense_county_covid_df['county'] = dense_county_covid_df['county'].str.lower()
dense_county_covid_df['state'] = dense_county_covid_df['state'].str.lower()

# rename 'cases' to 'total_cases'
dense_county_covid_df = dense_county_covid_df.rename(columns={'cases':'total_cases'})

# reset index
dense_county_covid_df = dense_county_covid_df.reset_index().drop(['index'],1)

# save county results to csv
dense_county_covid_df.to_csv("dense_county_covid.csv")

# check results
dense_county_covid_df.head(30)

          date     county     state  total_cases  new_cases  delta7  delta14
0   2020-03-11  baltimore  maryland            1       <NA>    <NA>     <NA>
1   2020-03-12  baltimore  maryland            1          0    <NA>     <NA>
2   2020-03-13  baltimore  maryland            2          1    <NA>     <NA>
3   2020-03-14  baltimore  maryland            3          1    <NA>     <NA>
4   2020-03-15  baltimore  maryland            3          0    <NA>     <NA>
5   2020-03-16  baltimore  maryland            4          1    <NA>     <NA>
6   2020-03-17  baltimore  maryland            4          0    <NA>     <NA>
7   2020-03-18  baltimore  maryland            7          3       6     <NA>
8   2020-03-19  baltimore  maryland           13          6      12     <NA>
9   2020-03-20  baltimore  maryland           13          0      11     <NA>
10  2020-03-21  baltimore  maryland           19          6      16     <NA>
11  2020-03-22  baltimore  maryland           28          9      25     <NA>
12  2020-03-23  baltimore  maryland           35          7      31     <NA>
13  2020-03-24  baltimore  maryland           42          7      38     <NA>
14  2020-03-25  baltimore  maryland           51          9      44       50
15  2020-03-26  baltimore  maryland           81         30      68       80
16  2020-03-27  baltimore  maryland          103         22      90      101
17  2020-03-28  baltimore  maryland          141         38     122      138
18  2020-03-29  baltimore  maryland          162         21     134      159
19  2020-03-30  baltimore  maryland          186         24     151      182
20  2020-03-31  baltimore  maryland          227         41     185      223
21  2020-04-01  baltimore  maryland          289         62     238      282
22  2020-04-02  baltimore  maryland          353         64     272      340
23  2020-04-03  baltimore  maryland          427         74     324      414
24  2020-04-04  baltimore  maryland          491         64     350      472
25  2020-04-05  baltimore  maryland          590         99     428      562
26  2020-04-06  baltimore  maryland          648         58     462      613
27  2020-04-07  baltimore  maryland          652          4     425      610
28  2020-04-08  baltimore  maryland          866        214     577      815
29  2020-04-09  baltimore  maryland          979        113     626      898

In [4]:
# Select data for sparse county data
sparse_state_county = [
    ('Virginia','Fairfax'),
    ('New Jersey','Camden'),
    ('Texas','Harris'),
    ('Ohio','Franklin'),
    ('Indiana','Marion'),
    ('Georgia','DeKalb'),
    ('Florida','Duval'),
    ('North Carolina','Wake'),
    ('Texas','Bexar')
]

In [5]:
# Process data for each sparse county

# Create new DataFrame to bring data for each county together
sparse_county_covid_df = pd.DataFrame()

for state, county in sparse_state_county:
    # Get the correct county data
    county_df = covid_df[(covid_df['state'] == state) & (covid_df['county'] == county)].reset_index().drop(['index'],1)

    # new_cases column
    # record the number of new cases for today
    county_df['new_cases'] = pd.Series(dtype=int)

    for i in range(1,len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-1,3]

        county_df.iloc[i,4] = current_cases - previous_cases

    # delta7 column
    # record the change in number of cases from 7 days ago to today
    county_df['delta7'] = pd.Series(dtype=int)

    for i in range(7, len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-7,3]

        county_df.iloc[i,5] = current_cases - previous_cases
    
    # delta14 column
    # record the change in number of cases from 7 days ago to today
    county_df['delta14'] = pd.Series(dtype=int)

    for i in range(14,len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-14,3]

        county_df.iloc[i,6] = current_cases - previous_cases

    # Add to final_df
    sparse_county_covid_df = pd.concat([sparse_county_covid_df,county_df])

# Convert float values to int
sparse_county_covid_df = sparse_county_covid_df.convert_dtypes()
sparse_county_covid_df.head(30)

# make all county and state names lowercase, remove secondary words like 'city'
sparse_county_covid_df['county'] = sparse_county_covid_df['county'].str.lower()
sparse_county_covid_df['state'] = sparse_county_covid_df['state'].str.lower()

# rename 'cases' to 'total_cases'
sparse_county_covid_df = sparse_county_covid_df.rename(columns={'cases':'total_cases'})

# reset index
sparse_county_covid_df = sparse_county_covid_df.reset_index().drop(['index'],1)

# save county results to csv
sparse_county_covid_df.to_csv("sparse_county_covid.csv")

# check results
sparse_county_covid_df.head(30)

          date   county     state  total_cases  new_cases  delta7  delta14
0   2020-03-07  fairfax  virginia            1       <NA>    <NA>     <NA>
1   2020-03-08  fairfax  virginia            2          1    <NA>     <NA>
2   2020-03-09  fairfax  virginia            4          2    <NA>     <NA>
3   2020-03-10  fairfax  virginia            4          0    <NA>     <NA>
4   2020-03-11  fairfax  virginia            4          0    <NA>     <NA>
5   2020-03-12  fairfax  virginia            4          0    <NA>     <NA>
6   2020-03-13  fairfax  virginia            6          2    <NA>     <NA>
7   2020-03-14  fairfax  virginia           10          4       9     <NA>
8   2020-03-15  fairfax  virginia           10          0       8     <NA>
9   2020-03-16  fairfax  virginia           10          0       6     <NA>
10  2020-03-17  fairfax  virginia           12          2       8     <NA>
11  2020-03-18  fairfax  virginia           14          2      10     <NA>
12  2020-03-19  fairfax  virginia           16          2      12     <NA>
13  2020-03-20  fairfax  virginia           16          0      10     <NA>
14  2020-03-21  fairfax  virginia           22          6      12       21
15  2020-03-22  fairfax  virginia           31          9      21       29
16  2020-03-23  fairfax  virginia           43         12      33       39
17  2020-03-24  fairfax  virginia           46          3      34       42
18  2020-03-25  fairfax  virginia           76         30      62       72
19  2020-03-26  fairfax  virginia          124         48     108      120
20  2020-03-27  fairfax  virginia          124          0     108      118
21  2020-03-28  fairfax  virginia          156         32     134      146
22  2020-03-29  fairfax  virginia          187         31     156      177
23  2020-03-30  fairfax  virginia          225         38     182      215
24  2020-03-31  fairfax  virginia          244         19     198      232
25  2020-04-01  fairfax  virginia          288         44     212      274
26  2020-04-02  fairfax  virginia          328         40     204      312
27  2020-04-03  fairfax  virginia          372         44     248      356
28  2020-04-04  fairfax  virginia          387         15     231      365
29  2020-04-05  fairfax  virginia          426         39     239      395