In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.simplefilter(action='ignore',category=FutureWarning)

covid_df = pd.read_csv("us_counties_covid19_daily.csv")
covid_df = covid_df.drop(['fips','deaths'],1)
covid_df.head()

         date     county       state  cases
0  2020-01-21  Snohomish  Washington      1
1  2020-01-22  Snohomish  Washington      1
2  2020-01-23  Snohomish  Washington      1
3  2020-01-24       Cook    Illinois      1
4  2020-01-24  Snohomish  Washington      1

In [2]:
# Select data for dense county data
dense_state_county = [
    ('Maryland','Baltimore'),
    ('New Jersey','Essex'),
    ('Illinois','Cook'),
    ('New Jersey','Union'),
    ('Virginia','Norfolk city'),
    ('New York','Nassau'),
    ('Virginia','Harrisonburg city')
]

In [3]:
# Process data for each dense county

# Create new DataFrame to bring data for each county together
dense_county_covid_df = pd.DataFrame()

for state, county in dense_state_county:
    # Get the correct county data
    county_df = covid_df[(covid_df['state'] == state) & (covid_df['county'] == county)].reset_index().drop(['index'],1)

    # new_cases column
    # record the number of new cases for today
    county_df['new_cases'] = pd.Series(dtype=int)

    # Set new_cases for first row = total_cases
    county_df.iloc[0,4] = county_df.iloc[0,3]

    for i in range(1,len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-1,3]

        county_df.iloc[i,4] = current_cases - previous_cases

    # delta7 column
    # record the change in number of cases from 7 days ago to today
    county_df['future_delta7'] = pd.Series(dtype=int)

    for i in range(0, len(county_df.index)-7):
        current_cases = county_df.iloc[i,3]
        future_cases = county_df.iloc[i+7,3]

        county_df.iloc[i,5] = future_cases - current_cases
    
    # delta14 column
    # record the change in number of cases from 7 days ago to today
    county_df['future_delta14'] = pd.Series(dtype=int)

    for i in range(0,len(county_df.index)-14):
        current_cases = county_df.iloc[i,3]
        future_cases = county_df.iloc[i+14,3]

        county_df.iloc[i,6] = future_cases - current_cases
    
    # remove secondary words like 'city' from county names
    for i in range(0,len(county_df.index)):
        county_df.iloc[i,1] = county.split(' ')[0]

    # Add to final_df
    dense_county_covid_df = pd.concat([dense_county_covid_df,county_df])

# Convert float values to int
dense_county_covid_df = dense_county_covid_df.convert_dtypes()
dense_county_covid_df.head(30)

# make all county and state names lowercase, remove secondary words like 'city'
dense_county_covid_df['county'] = dense_county_covid_df['county'].str.lower()
dense_county_covid_df['state'] = dense_county_covid_df['state'].str.lower()

# rename 'cases' to 'total_cases'
dense_county_covid_df = dense_county_covid_df.rename(columns={'cases':'total_cases'})

# reset index
dense_county_covid_df = dense_county_covid_df.reset_index().drop(['index'],1)

# save county results to csv
dense_county_covid_df.to_csv("data/covid/dense_county_covid.csv")

# check results
dense_county_covid_df.head(30)

,date,county,state,total_cases,new_cases,future_delta7,future_delta14
0,2020-03-11,baltimore,maryland,1,1,6,50
1,2020-03-12,baltimore,maryland,1,0,12,80
2,2020-03-13,baltimore,maryland,2,1,11,101
3,2020-03-14,baltimore,maryland,3,1,16,138
4,2020-03-15,baltimore,maryland,3,0,25,159
5,2020-03-16,baltimore,maryland,4,1,31,182
6,2020-03-17,baltimore,maryland,4,0,38,223
7,2020-03-18,baltimore,maryland,7,3,44,282
8,2020-03-19,baltimore,maryland,13,6,68,340
9,2020-03-20,baltimore,maryland,13,0,90,414
10,2020-03-21,baltimore,maryland,19,6,122,472
11,2020-03-22,baltimore,maryland,28,9,134,562
12,2020-03-23,baltimore,maryland,35,7,151,613
13,2020-03-24,baltimore,maryland,42,7,185,610
14,2020-03-25,baltimore,maryland,51,9,238,815
15,2020-03-26,baltimore,maryland,81,30,272,898
16,2020-03-27,baltimore,maryland,103,22,324,969
17,2020-03-28,baltimore,maryland,141,38,350,1032
18,2020-03-29,baltimore,maryland,162,21,428,1095
19,2020-03-30,baltimore,maryland,186,24,462,1175
20,2020-03-31,baltimore,maryland,227,41,425,1150
21,2020-04-01,baltimore,maryland,289,62,577,1201
22,2020-04-02,baltimore,maryland,353,64,626,1169
23,2020-04-03,baltimore,maryland,427,74,645,1149
24,2020-04-04,baltimore,maryland,491,64,682,1180
25,2020-04-05,baltimore,maryland,590,99,667,1149
26,2020-04-06,baltimore,maryland,648,58,713,1233
27,2020-04-07,baltimore,maryland,652,4,725,1280
28,2020-04-08,baltimore,maryland,866,214,624,1155
29,2020-04-09,baltimore,maryland,979,113,543,1162

In [4]:
# Verify end of data
dense_county_covid_df.tail(30)

,date,county,state,total_cases,new_cases,future_delta7,future_delta14
1903,2020-11-06,harrisonburg,virginia,3183,22,52,136
1904,2020-11-07,harrisonburg,virginia,3197,14,50,150
1905,2020-11-08,harrisonburg,virginia,3197,0,50,162
1906,2020-11-09,harrisonburg,virginia,3205,8,51,169
1907,2020-11-10,harrisonburg,virginia,3217,12,74,173
1908,2020-11-11,harrisonburg,virginia,3224,7,72,173
1909,2020-11-12,harrisonburg,virginia,3225,1,71,197
1910,2020-11-13,harrisonburg,virginia,3235,10,84,189
1911,2020-11-14,harrisonburg,virginia,3247,12,100,214
1912,2020-11-15,harrisonburg,virginia,3247,0,112,224
1913,2020-11-16,harrisonburg,virginia,3256,9,118,216
1914,2020-11-17,harrisonburg,virginia,3291,35,99,191
1915,2020-11-18,harrisonburg,virginia,3296,5,101,197
1916,2020-11-19,harrisonburg,virginia,3296,0,126,202
1917,2020-11-20,harrisonburg,virginia,3319,23,105,210
1918,2020-11-21,harrisonburg,virginia,3347,28,114,218
1919,2020-11-22,harrisonburg,virginia,3359,12,112,<NA>
1920,2020-11-23,harrisonburg,virginia,3374,15,98,<NA>
1921,2020-11-24,harrisonburg,virginia,3390,16,92,<NA>
1922,2020-11-25,harrisonburg,virginia,3397,7,96,<NA>
1923,2020-11-26,harrisonburg,virginia,3422,25,76,<NA>
1924,2020-11-27,harrisonburg,virginia,3424,2,105,<NA>
1925,2020-11-28,harrisonburg,virginia,3461,37,104,<NA>
1926,2020-11-29,harrisonburg,virginia,3471,10,<NA>,<NA>
1927,2020-11-30,harrisonburg,virginia,3472,1,<NA>,<NA>
1928,2020-12-01,harrisonburg,virginia,3482,10,<NA>,<NA>
1929,2020-12-02,harrisonburg,virginia,3493,11,<NA>,<NA>
1930,2020-12-03,harrisonburg,virginia,3498,5,<NA>,<NA>
1931,2020-12-04,harrisonburg,virginia,3529,31,<NA>,<NA>
1932,2020-12-05,harrisonburg,virginia,3565,36,<NA>,<NA>

In [5]:
# Select data for sparse county data
sparse_state_county = [
    ('Virginia','Fairfax'),
    ('New Jersey','Camden'),
    ('Texas','Harris'),
    ('Ohio','Franklin'),
    ('Indiana','Marion'),
    ('Georgia','DeKalb'),
    ('Florida','Duval'),
    ('North Carolina','Wake'),
    ('Texas','Bexar')
]

In [6]:
# Process data for each sparse county

# Create new DataFrame to bring data for each county together
sparse_county_covid_df = pd.DataFrame()

for state, county in sparse_state_county:
    # Get the correct county data
    county_df = covid_df[(covid_df['state'] == state) & (covid_df['county'] == county)].reset_index().drop(['index'],1)

    # new_cases column
    # record the number of new cases for today
    county_df['new_cases'] = pd.Series(dtype=int)

    # Set new_cases for first row = total_cases
    county_df.iloc[0,4] = county_df.iloc[0,3]

    for i in range(1,len(county_df.index)):
        current_cases = county_df.iloc[i,3]
        previous_cases = county_df.iloc[i-1,3]

        county_df.iloc[i,4] = current_cases - previous_cases

    # delta7 column
    # record the change in number of cases from 7 days ago to today
    county_df['future_delta7'] = pd.Series(dtype=int)

    for i in range(0, len(county_df.index)-7):
        current_cases = county_df.iloc[i,3]
        future_cases = county_df.iloc[i+7,3]

        county_df.iloc[i,5] = future_cases - current_cases
    
    # delta14 column
    # record the change in number of cases from 7 days ago to today
    county_df['future_delta14'] = pd.Series(dtype=int)

    for i in range(0,len(county_df.index)-14):
        current_cases = county_df.iloc[i,3]
        future_cases = county_df.iloc[i+14,3]

        county_df.iloc[i,6] = future_cases - current_cases

    # Add to final_df
    sparse_county_covid_df = pd.concat([sparse_county_covid_df,county_df])

# Convert float values to int
sparse_county_covid_df = sparse_county_covid_df.convert_dtypes()
sparse_county_covid_df.head(30)

# make all county and state names lowercase, remove secondary words like 'city'
sparse_county_covid_df['county'] = sparse_county_covid_df['county'].str.lower()
sparse_county_covid_df['state'] = sparse_county_covid_df['state'].str.lower()

# rename 'cases' to 'total_cases'
sparse_county_covid_df = sparse_county_covid_df.rename(columns={'cases':'total_cases'})

# reset index
sparse_county_covid_df = sparse_county_covid_df.reset_index().drop(['index'],1)

# save county results to csv
sparse_county_covid_df.to_csv("data/covid/sparse_county_covid.csv")

# check results
sparse_county_covid_df.head(30)

,date,county,state,total_cases,new_cases,future_delta7,future_delta14
0,2020-03-07,fairfax,virginia,1,1,9,21
1,2020-03-08,fairfax,virginia,2,1,8,29
2,2020-03-09,fairfax,virginia,4,2,6,39
3,2020-03-10,fairfax,virginia,4,0,8,42
4,2020-03-11,fairfax,virginia,4,0,10,72
5,2020-03-12,fairfax,virginia,4,0,12,120
6,2020-03-13,fairfax,virginia,6,2,10,118
7,2020-03-14,fairfax,virginia,10,4,12,146
8,2020-03-15,fairfax,virginia,10,0,21,177
9,2020-03-16,fairfax,virginia,10,0,33,215
10,2020-03-17,fairfax,virginia,12,2,34,232
11,2020-03-18,fairfax,virginia,14,2,62,274
12,2020-03-19,fairfax,virginia,16,2,108,312
13,2020-03-20,fairfax,virginia,16,0,108,356
14,2020-03-21,fairfax,virginia,22,6,134,365
15,2020-03-22,fairfax,virginia,31,9,156,395
16,2020-03-23,fairfax,virginia,43,12,182,445
17,2020-03-24,fairfax,virginia,46,3,198,486
18,2020-03-25,fairfax,virginia,76,30,212,494
19,2020-03-26,fairfax,virginia,124,48,204,566
20,2020-03-27,fairfax,virginia,124,0,248,653
21,2020-03-28,fairfax,virginia,156,32,231,790
22,2020-03-29,fairfax,virginia,187,31,239,821
23,2020-03-30,fairfax,virginia,225,38,263,939
24,2020-03-31,fairfax,virginia,244,19,288,963
25,2020-04-01,fairfax,virginia,288,44,282,1010
26,2020-04-02,fairfax,virginia,328,40,362,1047
27,2020-04-03,fairfax,virginia,372,44,405,1104
28,2020-04-04,fairfax,virginia,387,15,559,1246
29,2020-04-05,fairfax,virginia,426,39,582,1383

In [7]:
# Verify end of data
sparse_county_covid_df.tail(30)

,date,county,state,total_cases,new_cases,future_delta7,future_delta14
2454,2020-11-06,bexar,texas,67139,218,1249,5186
2455,2020-11-07,bexar,texas,67377,238,2428,5440
2456,2020-11-08,bexar,texas,67639,262,2415,6255
2457,2020-11-09,bexar,texas,68056,417,2192,6547
2458,2020-11-10,bexar,texas,68388,332,2152,7342
2459,2020-11-11,bexar,texas,68388,0,2518,8374
2460,2020-11-12,bexar,texas,68388,0,3001,8374
2461,2020-11-13,bexar,texas,68388,0,3937,8374
2462,2020-11-14,bexar,texas,69805,1417,3012,8618
2463,2020-11-15,bexar,texas,70054,249,3840,10015
2464,2020-11-16,bexar,texas,70248,194,4355,10938
2465,2020-11-17,bexar,texas,70540,292,5190,11098
2466,2020-11-18,bexar,texas,70906,366,5856,12231
2467,2020-11-19,bexar,texas,71389,483,5373,12508
2468,2020-11-20,bexar,texas,72325,936,4437,12888
2469,2020-11-21,bexar,texas,72817,492,5606,13090
2470,2020-11-22,bexar,texas,73894,1077,6175,<NA>
2471,2020-11-23,bexar,texas,74603,709,6583,<NA>
2472,2020-11-24,bexar,texas,75730,1127,5908,<NA>
2473,2020-11-25,bexar,texas,76762,1032,6375,<NA>
2474,2020-11-26,bexar,texas,76762,0,7135,<NA>
2475,2020-11-27,bexar,texas,76762,0,8451,<NA>
2476,2020-11-28,bexar,texas,78423,1661,7484,<NA>
2477,2020-11-29,bexar,texas,80069,1646,<NA>,<NA>
2478,2020-11-30,bexar,texas,81186,1117,<NA>,<NA>
2479,2020-12-01,bexar,texas,81638,452,<NA>,<NA>
2480,2020-12-02,bexar,texas,83137,1499,<NA>,<NA>
2481,2020-12-03,bexar,texas,83897,760,<NA>,<NA>
2482,2020-12-04,bexar,texas,85213,1316,<NA>,<NA>
2483,2020-12-05,bexar,texas,85907,694,<NA>,<NA>